### ISSUE TITLE
`damlc docs` generates wrong links for Types from stdlib

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#6039]
When using `daml damlc docs` to generate documentation from DAML code, types like `Text` (from `stdlib`) used to have a link leading to their description in the SDK documentation.
Since SDK 1.1.0 the anchors in the links are not valid any more, the link only leads to the start page of the stdlib documentation. 
The split into separate files per module in https://github.com/digital-asset/daml/pull/5636 has probably caused this. 

To see the issue, run the following commands:
```
$ daml new test-damldoc
$ cd test-damldoc
$ daml damlc docs daml/Maiin.daml -o test
$ cat test/Main.md
```
The generated `Main.md` will contain a link
`[Text](https://docs.daml.com/daml/stdlib/index.html#type-ghc-types-text-57703)`
which should instead be
`https://docs.daml.com/daml/stdlib/Prelude.html#type-ghc-types-text-57703`

**Comment by sofiafaro-da** [comment]
Thanks for the issue @jberthold-da!

This behavior is expected right now when generating damldocs outside the standard library.

This can be fixed (on our end) by shipping the anchor table for the stdlib with the SDK, and using it implicitly. For now, though, linking to index.html is the best effort that damldocs can do.

**Comment by jberthold-da** [comment]
Is it possible for us as end users to extract the anchor table in some way?
Then I could work around the problem until the implicit use is implemented.

**Comment by sofiafaro-da** [comment]
It's possible to generate the anchor table for the stdlib by using the `--output-anchor PATH` option (we can modify the bazel command to add the anchor table as an output) but there's no way to use the anchor table to generate the correct links at the moment.

**Comment by sofiafaro-da** [comment]
#6088 adds the bazel target `//compiler/damlc:daml-base-anchors.json` which is the anchor table for the standard library.

**Comment by sofiafaro-da** [comment]
@shayne-fletcher's work in  #6386 adds the `--input-anchor` flag and distributes the stdlib anchor table in the damlc runfiles. The only thing missing is to make the anchor table shipped with `damlc` be used by default.

**Comment by hurryabit** [comment]
This is fixed by now.

**Comment by akrmn** [comment]
While working on https://github.com/digital-asset/daml/pull/15446 I found that 

> The only thing missing is to make the anchor table shipped with `damlc` be used by default.

is still missing
