### ISSUE TITLE
When I change DAML code, I have to delete node_modules to get my UI working again

### ISSUE THREAD

**Issue by SamirTalwar-DA** [digital-asset/daml#6692]
When regenerating JavaScript from my DAML code, the package IDs change. Unfortunately, it seems to be cached in _ui/node_modules_, which means that my UI is now broken.

I can work around this by deleting _ui/node_modules_, but it's slow, and I tend to forget.

I'd like regenerating the JavaScript to automatically push the new code into my UI.

**Comment by SamirTalwar-DA** [comment]
I think we could use [Yarn workspaces][] as an elegant solution for this. If both _daml.js_ and _ui_ were workspaces, _ui_ could depend on _daml.js_ by path and Yarn wouldn't copy the files into the _ui/node_modules_ directory, which would allow for live updating.

[yarn workspaces]: https://classic.yarnpkg.com/en/docs/workspaces/

**Comment by cocreature** [comment]
You don’t have to delete node_modules. `yarn install --force --frozen-lockfile` works which is part of the GSG but I agree that this is almost as shitty.

**Comment by hurryabit** [comment]
This should be fixed by moving from `yarn` to `npm`. cc @robin-da

**Comment by cocreature** [comment]
It is only partially fixed. You no longer need to pass `--force` but you still need to run `npm install` again.
